# Workflow Name - Hello World
name: Hello World
# Trigger Workflow on push events
'on': push
# Workflow should have a Job named - hello-job
# a. Run Job on - ubuntu-latest runner
# b. Job has 1 step named - Echo text
# c. Run a command - echo "Hello, world!"
# Trigger Workflow on push event should execute successfully
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: echo "Hello, world!"
